In [1]:
import numpy as np
import pandas as pd

In [2]:
date = pd.read_csv('DataSets/D34/orders.csv')
time = pd.read_csv('DataSets/D34/messages.csv')

In [3]:
date.sample(5)

           date  product_id  city_id  orders
121  2018-08-30        7140       18      54
422  2019-11-24        6717        3       1
158  2019-12-16        2148       28      51
542  2019-06-10        2652       18      69
868  2018-09-01        3679        6       2

In [4]:
time.sample(5)

                    date                                                msg
996  2014-01-23 23:14:00            сельский п 23 ищу девушку для отношений
655  2014-02-17 01:44:00  Алена 22 познакомлюся с приятным парнем для об...
453  2012-11-11 01:40:00  Мужчин а  познакомится с  п арнем  СМС  095 06...
144  2013-06-10 00:40:00                      Карина сделает  М до 40 звони
187  2013-02-15 23:57:00  м 52 ищу не высокую ж для встреч днепр лев бер...

In [5]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [6]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

# Working with Dates

In [7]:
# Converting to datetime datatype
date['date'] = pd.to_datetime(date['date'])

In [8]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

## 1. Extract year

- .dt.year

In [9]:
date['date_year'] = date['date'].dt.year

date.sample(5)

          date  product_id  city_id  orders  date_year
650 2019-05-21        5626       22       1       2019
477 2018-08-08         383       25      22       2018
704 2019-11-12         468        0       5       2019
182 2019-05-26        1135       28       1       2019
809 2019-10-18        5371       22      17       2019

## 2. Extract Month

- .dt.month
- .dt.month_name()

In [10]:
date['date_month_no'] = date['date'].dt.month

date.head()

        date  product_id  city_id  orders  date_year  date_month_no
0 2019-12-10        5628       25       3       2019             12
1 2018-08-15        3646       14     157       2018              8
2 2018-10-23        1859       25       1       2018             10
3 2019-08-17        7292       25       1       2019              8
4 2019-01-06        4344       25       3       2019              1

In [ ]:
date['date_month_name'] = date['date'].dt.month_name()

date.head()

## Extract Days

- .dt.day
- .dt.dayofweek
- .dt.day_name()

In [11]:
date['date_day'] = date['date'].dt.day

date.head()

        date  product_id  city_id  orders  date_year  date_month_no  date_day
0 2019-12-10        5628       25       3       2019             12        10
1 2018-08-15        3646       14     157       2018              8        15
2 2018-10-23        1859       25       1       2018             10        23
3 2019-08-17        7292       25       1       2019              8        17
4 2019-01-06        4344       25       3       2019              1         6

In [12]:
# day of week
date['date_dow'] = date['date'].dt.dayofweek

date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_day,date_dow
0,2019-12-10,5628,25,3,2019,12,10,1
1,2018-08-15,3646,14,157,2018,8,15,2
2,2018-10-23,1859,25,1,2018,10,23,1
3,2019-08-17,7292,25,1,2019,8,17,5
4,2019-01-06,4344,25,3,2019,1,6,6

In [13]:
# day of week - name

date['date_dow_name'] = date['date'].dt.day_name()

date.drop(columns=['product_id','city_id','orders']).head()

        date  date_year  date_month_no  date_day  date_dow date_dow_name
0 2019-12-10       2019             12        10         1       Tuesday
1 2018-08-15       2018              8        15         2     Wednesday
2 2018-10-23       2018             10        23         1       Tuesday
3 2019-08-17       2019              8        17         5      Saturday
4 2019-01-06       2019              1         6         6        Sunday

In [14]:
# is weekend?

date['date_is_weekend'] = np.where(date['date_dow_name'].isin(['Sunday', 'Saturday']), 1,0)

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_day,date_dow,date_dow_name,date_is_weekend
0,2019-12-10,2019,12,10,1,Tuesday,0
1,2018-08-15,2018,8,15,2,Wednesday,0
2,2018-10-23,2018,10,23,1,Tuesday,0
3,2019-08-17,2019,8,17,5,Saturday,1
4,2019-01-06,2019,1,6,6,Sunday,1

## Extract week of the year

- .dt.isocalendar().week

In [17]:
date['date_week'] = date['date'].dt.isocalendar().week

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_day,date_dow,date_dow_name,date_is_weekend,date_week
0,2019-12-10,2019,12,10,1,Tuesday,0,50
1,2018-08-15,2018,8,15,2,Wednesday,0,33
2,2018-10-23,2018,10,23,1,Tuesday,0,43
3,2019-08-17,2019,8,17,5,Saturday,1,33
4,2019-01-06,2019,1,6,6,Sunday,1,1

## Extract Quarter

- .dt.quarter

In [18]:
date['quarter'] = date['date'].dt.quarter

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_day,date_dow,date_dow_name,date_is_weekend,date_week,quarter
0,2019-12-10,2019,12,10,1,Tuesday,0,50,4
1,2018-08-15,2018,8,15,2,Wednesday,0,33,3
2,2018-10-23,2018,10,23,1,Tuesday,0,43,4
3,2019-08-17,2019,8,17,5,Saturday,1,33,3
4,2019-01-06,2019,1,6,6,Sunday,1,1,1

## Extract Semester

In [19]:
date['semester'] = np.where(date['quarter'].isin([1,2]), 1, 2)

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_day,date_dow,date_dow_name,date_is_weekend,date_week,quarter,semester
0,2019-12-10,2019,12,10,1,Tuesday,0,50,4,2
1,2018-08-15,2018,8,15,2,Wednesday,0,33,3,2
2,2018-10-23,2018,10,23,1,Tuesday,0,43,4,2
3,2019-08-17,2019,8,17,5,Saturday,1,33,3,2
4,2019-01-06,2019,1,6,6,Sunday,1,1,1,1

## Extract Time elapsed between dates

In [20]:
import datetime

today = datetime.datetime.today()

today

datetime.datetime(2026, 7, 21, 17, 23, 8, 826638)

In [21]:
today - date['date']

0     2415 days 17:23:08.826638
1     2897 days 17:23:08.826638
2     2828 days 17:23:08.826638
3     2530 days 17:23:08.826638
4     2753 days 17:23:08.826638
                 ...
995   2843 days 17:23:08.826638
996   2784 days 17:23:08.826638
997   2632 days 17:23:08.826638
998   2697 days 17:23:08.826638
999   2471 days 17:23:08.826638
Name: date, Length: 1000, dtype: timedelta64[ns]

In [22]:
(today - date['date']).dt.days

0      2415
1      2897
2      2828
3      2530
4      2753
       ...
995    2843
996    2784
997    2632
998    2697
999    2471
Name: date, Length: 1000, dtype: int64

In [26]:
# Months passed

np.round((today - date['date']) / np.timedelta64(1, 'D') / 30.44, 0)  # 30.44 is average days per month (365.25/12)

0      79.0
1      95.0
2      93.0
3      83.0
4      90.0
       ...
995    93.0
996    91.0
997    86.0
998    89.0
999    81.0
Name: date, Length: 1000, dtype: float64

In [27]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [28]:
# Converting to datetime datatype
time['date'] = pd.to_datetime(time['date'])

In [29]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [30]:
time['hour'] = time['date'].dt.hour
time['min'] = time['date'].dt.minute
time['sec'] = time['date'].dt.second

time.head()

,date,msg,hour,min,sec
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0

## Extract Time part

In [31]:
time['time'] = time['date'].dt.time

time.head()

,date,msg,hour,min,sec,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00

## Time difference

In [32]:
today - time['date']

0     4601 days 16:33:08.826638
1     4465 days 17:43:08.826638
2     4951 days 17:02:08.826638
3     4253 days 16:52:08.826638
4     4650 days 18:12:08.826638
                 ...
995   5240 days 16:33:08.826638
996   4561 days 18:09:08.826638
997   5026 days 17:46:08.826638
998   5142 days 17:49:08.826638
999   4414 days 17:58:08.826638
Name: date, Length: 1000, dtype: timedelta64[ns]

In [33]:
# in seconds

(today - time['date'])/np.timedelta64(1,'s')

0      3.975860e+08
1      3.858398e+08
2      4.278277e+08
3      3.675199e+08
4      4.018255e+08
           ...
995    4.527956e+08
996    3.941357e+08
997    4.343104e+08
998    4.443329e+08
999    3.814343e+08
Name: date, Length: 1000, dtype: float64

In [34]:
# in minutes

(today - time['date'])/np.timedelta64(1,'m')

0      6.626433e+06
1      6.430663e+06
2      7.130462e+06
3      6.125332e+06
4      6.697092e+06
           ...
995    7.546593e+06
996    6.568929e+06
997    7.238506e+06
998    7.405549e+06
999    6.357238e+06
Name: date, Length: 1000, dtype: float64

In [35]:
# in hours

(today - time['date'])/np.timedelta64(1,'h')

0      110440.552452
1      107177.719119
2      118841.035785
3      102088.869119
4      111618.202452
           ...
995    125776.552452
996    109482.152452
997    120641.769119
998    123425.819119
999    105953.969119
Name: date, Length: 1000, dtype: float64